# Generated by Django 5.0.6 on 2024-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='ppost',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
