# Generated by Django 5.0.6 on 2024-05-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_category_rename_text_post_ppost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ppost',
            new_name='post',
        ),
    ]
