# Generated by Django 5.0.6 on 2024-05-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
